services:
  weather_app:
    build:
      context: .
    container_name: weather_app_container
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    depends_on:
      - db
      - redis
  redis:
    image: redis:latest
    container_name: weather_app_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
  db:
    image: postgres:latest
    container_name: weather_app_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: weatherdb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: test@postgres.com
      PGADMIN_DEFAULT_PASSWORD: 123456
    depends_on:
      - db
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  db_data:
  redis_data:
  pgadmin-data:
